- name: PROVISION VPC SUBNETS & F5 INSTANCES
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - ../creds/big_creds.yaml

  vars: 
    uri_method: POST
  
  tasks: 
  - name: AS3 declaration
    uri:
      url: https://108.128.216.12/mgmt/shared/appsvcs/declare
      user: "{{ bigip_user }}"
      password: "{{ bigip_pass }}"
      method: POST
      body: "{{ lookup('file','./AS3-declarations/simple-as3.json') }}"
      force_basic_auth: yes
      validation_certs: no
      status_code: 200
      body_format: json